# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20f34381fa1542793e5c460e072a350921bf21affa6fbede582dbae41d8d0add7bfe7408c0de2f632278b1c24c33d3aa94512ca179bdf2ed266e3fa1fb337bd2

test:
  secret_key_base: 4a69ad881396cc2fcea3da3cd040fe177c23bf6514cb6938125d1ad5b1b50b2411a393ed1ea439b89a797f3b934d6d2b24bb1ffde14dfb06ce0860e821d785b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
